name: graceful
description: Handle exit signals gracefully and pipe stdio to log files.
version: 1.0.0
repository: https://github.com/doodlezucc/dart_graceful

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
