name: graceful
description: Handle exit signals properly and pipe stdio to log files.
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
